---
title: "Graph examples"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE, message = FALSE)
# https://dinov-tokyo.github.io/flexdashboard_ex/
# https://ramikrispin.github.io/2020/09/deploying-flexdashboard-on-github-pages/
# https://plotly.com/r/
library(flexdashboard)
library(tidyverse)
library(echarts4r)
library(nycflights13) # data
library(wesanderson)
library(plotly)

library(ggridges)
library(ggplot2)
library(ggrepel)

```


1st example
=====================================   


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

Animals <- c("giraffes", "orangutans", "monkeys")
SF_Zoo <- c(20, 14, 23)
LA_Zoo <- c(12, 18, 29)
data <- data.frame(Animals, SF_Zoo, LA_Zoo)

fig <- plot_ly(data, x = ~Animals, y = ~SF_Zoo, type = 'bar', name = 'SF Zoo')
fig <- fig %>% add_trace(y = ~LA_Zoo, name = 'LA Zoo')
fig <- fig %>% layout(yaxis = list(title = 'Count'), barmode = 'group')

fig
```

### Chart NY flight

```{r flight}

top_destinations <- flights %>% 
  count(dest) %>% 
  top_n(15, n) %>% 
  arrange(n)

top_destinations %>%
  e_charts(x = dest) %>%
  e_bar(n, legend = FALSE, name = "Flights") %>% 
  e_labels(position = "right") %>% 
  e_tooltip() %>% 
  e_title("Flights by destination", "Top 15 destinations") %>% 
  e_flip_coords() %>% 
  e_y_axis(splitLine = list(show = FALSE)) %>% 
  e_x_axis(show = FALSE) %>% 
  e_toolbox_feature(
    feature = "saveAsImage",
    title = "Save as image"
  )

```




Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
library(plotly)
library(tidyr)
library(plyr)

data <- spread(Orange, Tree, circumference)
data <- rename(data, c("1" = "Tree1", "2" = "Tree2", "3" = "Tree3", "4" = "Tree4", "5" = "Tree5"))

fig <- plot_ly(data, x = ~age, y = ~Tree1, type = 'scatter', mode = 'lines', name = 'Tree 1')
fig <- fig %>% add_trace(y = ~Tree2, name = 'Tree 2')
fig <- fig %>% add_trace(y = ~Tree3, name = 'Tree 3')
fig <- fig %>% add_trace(y = ~Tree4, name = 'Tree 4')
fig <- fig %>% add_trace(y = ~Tree5, name = 'Tree 5')

fig
```

### Chart C

```{r}


library(lubridate)
library(ggtext)
library(gtrendsR)
library(showtext)

trend_raw <- gtrends("Trump", time = "2020-01-01 2020-12-31")

trend <- trend_raw %>% 
  collapse::unlist2d() %>% 
  as_tibble() %>% 
  filter(.id == "interest_over_time") %>% 
  select(date, hits) %>% 
  mutate(
    tiles = 1,
    date = as_date(date),
    hits = hits %>% 
      str_replace("<1", "0") %>% 
      as.numeric()
  )

trend %>% 
  ggplot(aes(date, tiles, height = 50*tiles, fill = hits)) + 
  geom_tile() + 
  scale_x_date(date_breaks = "months", date_labels = month.abb) +
  scale_y_continuous(limits = c(-100, NA)) +
  coord_polar(start = 0)

```

2nd example
=====================================   


Column
-----------------------------------------------------------------------

### Lollipop graph

```{r lollipop}


mtcars$car <- row.names(mtcars)

mtcars_mean <- mtcars %>%
  arrange(disp) %>%
  mutate(mean_disp = mean(disp),
         flag = ifelse(disp - mean_disp > 0, TRUE, FALSE),
         car = factor(car, levels = .$car))

ggplot(mtcars_mean, aes(x = disp, y = car, color = flag)) +
  geom_segment(aes(x = mean_disp, y = car, xend = disp, yend = car)) +
  geom_point(size = 5)+
  scale_colour_manual(values = c("red", "green")) +
  labs(title = "Displacement by Car") 

```

### Probalility density plot

```{r prob}

# devtools::install_github("tegedik/pdplot2")
library(pdplot2)

pdplot2(seq(-10, 10, 0.01), mean=c(1,0,-1), sd=c(0.5,1.5,2.5), type="normal", show.color=TRUE)





```


Row
----------------------------------------------------

### table1


```{r table1}

library(ggridges)
 
pal <- wes_palette(7, name = "Zissou1", type = "continuous")

data_url <- url("https://raw.githubusercontent.com/billynguyenlss/TMDB-Box/master/data/personal%20additional%20data/full_additional_features_2.csv")
blockbuster_data <- read.csv(data_url, na.strings=c("", '#N/A', '[]', '0'))

blockbuster_data %>% 
  select("genres1", "new_revenue") %>% 
  filter(genres1 %in% c("Action", "Drama", "Science Fiction", "Animation", "Mystery", "War", "Crime")) %>% 
  ggplot(aes(x = new_revenue, y = genres1, fill = genres1)) +
  geom_density_ridges(jittered_points = TRUE, 
                      position = position_points_jitter(width = 0.02, yoffset = -.25, seed = 1),
                      alpha = 0.6)  + 
  theme(legend.position = "none",
        axis.text.y = element_text(angle = 45, hjust = 1)) +
  scale_x_continuous(
      labels = scales::number_format(accuracy = 1,
                                     decimal.mark = ',')) +
  labs(title    = "Blockbusters",
       x = "New revenue",
       y = "Genres") +
  xlim(-10000, 50000000) +
  scale_fill_manual(values = pal) +
  theme_minimal()


```


### time line plot

```{r timeline}


library(scales)
library(lubridate)

df <-data.frame(
  month=c(6,7,8,9,10,1,2,5,1,4,6), 
  year=c(2015,2015,2015,2015,2015,2016,2016,2016,2018,2018,2018),
  check=c("c1","c2","c3","c4","c5","c6","c7","c8","c9","c10","c11"),
  eval=c("good","good","good","bad","bad","good","bad","good","good","good","bad")
  )

df$date <- with(df, ymd(sprintf('%04d%02d%02d', year, month, 1)))
df <- df[with(df, order(date)), ]

status_levels <- c("good", "bad")
status_colors <- c("#0070C0", "#00B050")

df$status <- factor(df$eval, levels=status_levels, ordered=TRUE)


positions <- c(0.5, -0.5, 1.0, -1.0, 1.5, -1.5)
directions <- c(1, -1)

line_pos <- data.frame(
  "date"=unique(df$date),
  "position"=rep(positions, length.out=length(unique(df$date))),
  "direction"=rep(directions, length.out=length(unique(df$date)))
)

df <- merge(x=df, y=line_pos, by="date", all = TRUE)
df <- df[with(df, order(date, status)), ]

text_offset <- 0.05

df$month_count <- ave(df$date==df$date, df$date, FUN=cumsum)
df$text_position <- (df$month_count * text_offset * df$direction) + df$position

month_buffer <- 2

month_date_range <- seq(min(df$date) - months(month_buffer), max(df$date) + months(month_buffer), by='month')
month_format <- format(month_date_range, '%b')
month_df <- data.frame(month_date_range, month_format)


year_date_range <- seq(min(df$date) - months(month_buffer), max(df$date) + months(month_buffer), by='year')
year_date_range <- as.Date(
  intersect(
    ceiling_date(year_date_range, unit="year"),
    floor_date(year_date_range, unit="year")
  ),  origin = "1970-01-01"
)
year_format <- format(year_date_range, '%Y')
year_df <- data.frame(year_date_range, year_format)


### PLOT ####

timeline_plot<-ggplot(df,aes(x=date,y=0, col=status, label=check))
timeline_plot<-timeline_plot+labs(col="check")
timeline_plot<-timeline_plot+scale_color_manual(values=status_colors, labels=status_levels, drop = FALSE)
timeline_plot<-timeline_plot+theme_classic()

# Plot horizontal black line for timeline
timeline_plot<-timeline_plot+geom_hline(yintercept=0, 
                                        color = "black", size=0.3)

# Plot vertical segment lines for milestones
timeline_plot<-timeline_plot+geom_segment(data=df[df$month_count == 1,], aes(y=position,yend=0,xend=date), color='black', size=0.2)

# Plot scatter points at zero and date
timeline_plot<-timeline_plot+geom_point(aes(y=0), size=3)

# Don't show axes, appropriately position legend
timeline_plot<-timeline_plot+theme(axis.line.y=element_blank(),
                                   axis.text.y=element_blank(),
                                   axis.title.x=element_blank(),
                                   axis.title.y=element_blank(),
                                   axis.ticks.y=element_blank(),
                                   axis.text.x =element_blank(),
                                   axis.ticks.x =element_blank(),
                                   axis.line.x =element_blank(),
                                   legend.position = "bottom"
)

# Show text for each month
timeline_plot<-timeline_plot+geom_text(data=month_df, aes(x=month_date_range,y=-0.1,label=month_format),size=2.5,vjust=0.5, color='black', angle=90)
# Show year text
timeline_plot<-timeline_plot+geom_text(data=year_df, aes(x=year_date_range,y=-0.2,label=year_format, fontface="bold"),size=2.5, color='black')
# Show text for each milestone
timeline_plot<-timeline_plot+geom_text(aes(y=text_position,label=check),size=2.5)

ggplotly(timeline_plot)
#print(timeline_plot)


```

Column
-----------------------------------------------------------------------

### ggpmisc

```{r radar}

library(ggpmisc)
library(broom)

ggplot(lynx, as.numeric = FALSE) + 
  geom_line() + 
  stat_peaks(colour = "green") +
  stat_peaks(geom = "text", colour = "blue", size = 7, angle = 70, hjust = -0.1, x.label.fmt = "%Y") +
  stat_peaks(geom = "rug", colour = "red", sides = "b") +
  expand_limits(y = 8000)

```

### pliman

```{r pliman}

library(pliman)

leaves <- image_import(image_pliman("la_leaves.JPG"))
image_show(leaves)

```

3rd example
=====================================   

Column
-----------------------------------------------------------------------

### NOAA Plot


```{r worldmet}

library(worldmet)
library(openair)
met_braunschweig <- importNOAA(code = "103480-99999", year =2020)
windRose(met_braunschweig)

```

### US Troops

```{r troopUS}

library(troopdata)

hostlist <- c("JPN", "GBR", "CAN")
US_troops <- get_troopdata(host = hostlist, startyear = 1970, endyear = 2020)
US_troops %>% 
  ggplot()+
  geom_point(aes(year, troops, col=countryname))+
  scale_color_manual(values = wes_palette("Royal1"))

```

Column
------------------------------------------------------------------------

### ggbeeswarm


```{r ggbeeswarm}

library(ggbeeswarm)
library(gghalves)

ggplot(mpg,aes(class, hwy, col=factor(class))) + 
  geom_beeswarm(size=1.4)+
  geom_half_boxplot(side="l")


```

### ggimg

```{r ggimg}

library(ggimg)


posters <- mutate(posters,
                  path = file.path(system.file("extdata", package="ggimg"), img)
)

ggplot(posters) +
  geom_rect_img(aes(
    xmin = year - 0.5,
    xmax = year + 0.5,
    ymin = stars - 0.25,
    ymax = stars + 0.25,
    img = path
  )) +
  theme_minimal() +
  labs(x="Released Year",
       y="Rated Star") 


```

Column
--------------------------------------------------------------- 
### Manu color palette

```{r manu}

library(Manu)

ymin <- min(iris$Sepal.Length)
ymax <- max(iris$Sepal.Length)

ggplot(iris) +
  geom_quasirandom(aes(x = factor(Species), y = Sepal.Length, colour = factor(Species))) +
  xlab("Species") +
  ylab("Sepal.Length") +
  theme_bw() +
  scale_y_continuous(limits = c(ymin, ymax)) #+
  scale_colour_manual(values = get_pal("Hoiho"))

```

### Wes andersen pallete

```{r pallete}

library("wesanderson")
ggplot(mtcars, aes(disp, fill=factor(vs))) +  
  geom_histogram() +
  scale_fill_manual(values = wes_palette("BottleRocket1"))

```

4th graph example 
=====================================


Column
-----------------------------------------------------------------------

### ggside

```{r ggside}

library(ggside)
library(tidyverse)
library(tidyquant)
library(palmerpenguins)

data(penguins)

p2<-penguins %>%
  drop_na() %>% 
  ggplot(aes(bill_length_mm, bill_depth_mm, color = species)) +
  geom_point(size = 2, alpha = 0.3) +
  geom_smooth(aes(color = NULL), se=TRUE) +
  geom_xsidedensity(
    aes(
      y    = after_stat(density),
      fill = species
    ),
    alpha    = 0.5,
    size     = 1,
    position = "stack"
  ) +
  geom_ysidedensity(
    aes(
      x    = after_stat(density),
      fill = species
    ),
    alpha    = 0.5,
    size     = 1,
    position = "stack"
  ) +
  scale_color_tq() +
  scale_fill_tq() +
  theme_tq() +
  labs(title = "Palmerpenguins by Species" ,
       subtitle = "Density Plot",
       x = "Bill Length mm", y = "Bill Depth mm") +  theme(
         ggside.panel.scale.x = 0.4,
         ggside.panel.scale.y = 0.4
       )
plot(p2)


```

### Sabre

```{r sabre}

library(sabre)
library(sf)

data("regions1")
data("regions2")

regions_vm = vmeasure_calc(x = regions1, y = regions2, x_name = z, y_name = z)

plot(regions_vm$map1["rih"], main = "Map1: rih")

```

Column
-----------------------------------------------------------------------

### ggfun

```{r ggfun}

library(ggfun)

p <- ggplot(mtcars, aes(mpg, disp, color=factor(cyl), size=cyl)) +
  geom_point()
p + theme(legend.background=element_roundrect(color="#808080", linetype=2))

```

### cowplot

```{r cowplot}

library(cowplot)
library(modeldata)

data(penguins)

p1 <- ggplot(penguins, aes(bill_length_mm, body_mass_g, color = species)) + 
  geom_point()

p2 <- ggplot(penguins, aes(bill_depth_mm, body_mass_g, color = species)) + 
  geom_point()

plot_grid(p1, p2, labels = c('Length', 'Depth'), label_size = 16)

```


Column
-----------------------------------------------------------------------
### see

```{r see}

library(see)

p1 <- ggplot(iris, aes(x = Species, y = Sepal.Length, fill = Species)) +
  geom_boxplot() +
  theme_modern(axis.text.angle = 45) +
  scale_fill_material_d()

p2 <- ggplot(iris, aes(x = Species, y = Sepal.Length, fill = Species)) +
  geom_violin() +
  theme_modern(axis.text.angle = 45) +
  scale_fill_material_d(palette = "ice")

p3 <- ggplot(iris, aes(x = Petal.Length, y = Petal.Width, color = Sepal.Length)) +
  geom_point2() +
  theme_modern() +
  scale_color_material_c(palette = "rainbow")

plots(p1, p2, p3, n_columns = 2)


```

### correlation

```{r correlation}


library(see) 
library(ggraph)
library(correlation)

diamonds %>%
  correlation(partial = TRUE) %>%
  plot()


```


5th graph example 
=====================================


Column
-----------------------------------------------------------------------

### Ghibli

```{r gihbli}

library(ghibli)

mtcars %>% ggplot(aes(drat, mpg, color = carb)) +
  geom_jitter(size = 2) +
  theme_minimal() +
  scale_colour_ghibli_c("YesterdayLight", direction = -1)

```

### calendR

```{r calendR}

library(calendR)
calendR(year = 2020,
        month = 2,  
        start = "M",
        special.days = c(1, 6, 18, 22),
        special.col = "#b5f222",
        text = c("Holiday", "Running", "Class"), 
        text.pos = c(7, 16, 25),
        text.size = 4,
        text.col = 2,
        lunar = TRUE,         
        lunar.col = "gray60", 
        lunar.size = 7)       


```


Column
-----------------------------------------------------------------------

### gtExtras

```{r gtExtras}
library(gtExtras)
library(gt)

gtcars %>%
  head(13) %>%
  dplyr::select(mfr, model, year, bdy_style, mpg_h, hp, trq) %>%
  dplyr::mutate(mpg_h = rnorm(n = dplyr::n(), mean = 22, sd = 1)) %>%
  gt() %>%
  opt_table_lines() %>%
  fmt_symbol_first(column = mfr, symbol = "&#x24;", last_row_n = 6) %>%
  fmt_symbol_first(column = year, suffix = "FY") %>%
  fmt_symbol_first(column = mpg_h, symbol = "&#37;", decimals = 1) %>%
  fmt_symbol_first(hp, symbol = "&#176;", suffix = "F", symbol_first = TRUE) %>% 
  fmt_symbol_first(trq, suffix = "N/m", symbol_first = TRUE) %>%
  gt_color_rows(
    mpg_h:trq, palette = c("white", "blue"),
    use_paletteer = FALSE)


```


Interactive graph example 
=====================================


Column
-----------------------------------------------------------------------
```{r ggiraph1, include=FALSE}

library(tidycensus)
library(ggiraph)
library(patchwork)

vt_income <- get_acs(
  geography = "county",
  variables = "B19013_001",
  state = "VT",
  year = 2019,
  geometry = TRUE
) %>%
  mutate(NAME = str_remove(NAME, " County, Vermont"))


```

Column
------------------------------------------------------------------

```{r ggiraph}

# https://gist.github.com/walkerke/3628171efae66421c299c9f2dbee0f34

vt_map <- ggplot(vt_income, aes(fill = estimate)) + 
  geom_sf_interactive(aes(data_id = GEOID)) + 
  scale_fill_distiller(palette = "Greens",
                       direction = 1, 
                       guide = FALSE) + 
  theme_void()

vt_plot <- ggplot(vt_income, aes(x = estimate, y = reorder(NAME, estimate), 
                                 fill = estimate)) +
  geom_errorbarh(aes(xmin = estimate - moe, xmax = estimate + moe)) +
  geom_point_interactive(color = "black", size = 4, shape = 21,
                         aes(data_id = GEOID)) +
  scale_fill_distiller(palette = "Greens", direction = 1,
                       labels = scales::dollar) + 
  labs(title = "Household income by county in Vermont",
       subtitle = "2015-2019 American Community Survey",
       y = "",
       x = "ACS estimate (bars represent margin of error)",
       fill = "ACS estimate") + 
  theme_minimal()

girafe(ggobj = vt_map + vt_plot, width_svg = 10, height_svg = 4) %>%
  girafe_options(opts_hover(css = "fill:cyan;"))



```

Column
-----------------------------------------------------------------------
```{r gt}


library(tidyverse)
library(gt)
library(gapminder)


gapminder %>% 
  filter(year=="1997") %>% 
  gt(
    groupname_col = "continent",
    rowname_col = "country"
  ) %>% 
  data_color(
    columns = vars(`lifeExp`, `pop`, `gdpPercap`),
    colors = scales::col_numeric(
      paletteer::paletteer_d(
        palette = "ggsci::red_material") %>% as.character(),
      domain = NULL
    )
  )



```



Crosstalk example
=====================================   

```{r table}

library(threejs)
library(crosstalk)
library(DT)


data(LeMis)

sd = SharedData$new(data.frame(Name = V(LeMis)$label))
bscols(
  graphjs(LeMis, brush=TRUE, crosstalk=sd),
  datatable(sd, rownames=FALSE, options=list(dom='tp')
            )
)



```